language: php
php:
    - 5.4
    - 5.5
    - 5.6
env:
  - DB=mysql

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - mkdir -p build/logs

script:
  - phpunit -c app --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    -  a.vara.1986@gmail.com
