crawler_homepage:
    path:     /hello/{name}
    defaults: { _controller: CrawlerBundle:Default:index }
website_read:
    path:     /website/{id}/{token}
    defaults: { _controller: CrawlerBundle:Website:read }
    methods:  [GET]
website_read2:
    path:     /website/{id}
    defaults: { _controller: CrawlerBundle:Website:read }
    methods:  [GET]
website_create:
    path:     /website/
    defaults: { _controller: CrawlerBundle:Website:create }
    methods:  [POST]
css_read:
    path:     /css/{id}/{token}
    defaults: { _controller: CrawlerBundle:Css:read }
    methods:  [GET]
css_read2:
    path:     /css/{id}
    defaults: { _controller: CrawlerBundle:Css:read }
    methods:  [GET]
css_create:
    path:     /css/
    defaults: { _controller: CrawlerBundle:Css:create }
    methods:  [POST]
#css_create2:
#    path:     /css/
#    defaults: { _controller: CrawlerBundle:Css:create }
#    methods:  [GET]